# Site settings
title: International Watch Repair
email: kim.rick@gmail.com
url: http://y7kim.github.io/hisao/
description: "International Watch Repair & Service, North Vancouver - At International Watch Repair & Service we have the expertise to repair your broken watch. As a certified master watchmaker proudly serving North Vancouver for over 25 years, we stand behind our work and make sure you are completely satisfied. Is your watch battery dead? No problem! We can replace a battery fast and convenient for you."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
