# Site settings
title: International Watch Repair
email: kim.rick@gmail.com
url: http://http://internationalwatchrepair.ca
baseurl:
description: "International Watch Repair & Service, North Vancouver - At International Watch Repair & Service we have the expertise to repair your broken watch. As a certified master watchmaker proudly serving North Vancouver for over 25 years, we stand behind our work and make sure you are completely satisfied. Is your watch battery dead? No problem! We can replace a battery fast and convenient for you."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#fff'

# Footer settings
footer: "International Watch Repair, 1915 Lonsdale Ave, North Vancouver, BC V7M 2K3"

# Hours

hours:
  Monday: 2:00pm - 5:30pm
  Tuesday: 10:00am - 5:30pm
  Wednesday: 10:00am - 5:30pm
  Thursday: 2:00pm - 5:30pm
  Friday: 10:00am - 5:30pm
  Saturday: 10:00am - 5:00pm
  Sunday: Closed
  Holidays: Closed

# Build settings
markdown: kramdown
permalink: pretty
